/*
 * COA Template for a Colombian Personal Workspace, built on the commercial PUC
 * (Decreto 2650 de 1993). Codes up to six digits are the decree's own; eight-digit
 * codes are auxiliaries the decree lets each entity add from the seventh digit
 * (Art. 7), used here for personal concepts the commercial PUC has no subaccount for.
 * Cohesive data file: one template, one version; see ADR-0082.
 */
import type { ChartOfAccountsTemplate } from "../types";

export const coPucPersonalTemplate = {
  version: "co-puc-personal@1",
  natureByClass: {
    "1": "Asset",
    "2": "Liability",
    "3": "Equity",
    "4": "Revenue",
    "5": "Expense",
  },
  defaults: { expense: "51959595", income: "42959595", openingBalance: "313001" },
  financialAccountParents: {
    cash: "110505",
    bankAccount: "111005",
    savingsAccount: "112005",
    creditCard: "210510",
    loan: "210510",
  },
  accounts: [
    // 1 Activo
    { code: "122505", name: "Certificados de depósito a término (CDT)", use: "general" },
    { code: "124505", name: "Fideicomisos de inversión moneda nacional", use: "general" },
    { code: "133005", name: "Anticipos a proveedores", use: "general" },
    { code: "134505", name: "Dividendos y participaciones por cobrar", use: "general" },
    { code: "134510", name: "Intereses por cobrar", use: "general" },
    { code: "134530", name: "Arrendamientos por cobrar", use: "general" },
    { code: "137005", name: "Préstamos a particulares con garantía real", use: "general" },
    { code: "137010", name: "Préstamos a particulares con garantía personal", use: "general" },
    { code: "138025", name: "Pagos por cuenta de terceros", use: "general" },
    { code: "150405", name: "Terrenos urbanos", use: "general" },
    { code: "151605", name: "Edificios", use: "general" },
    { code: "152405", name: "Muebles y enseres", use: "general" },
    { code: "152805", name: "Equipos de procesamiento de datos", use: "general" },
    { code: "154005", name: "Autos, camionetas y camperos", use: "general" },
    { code: "154030", name: "Motocicletas", use: "general" },
    { code: "159205", name: "Depreciación acumulada de construcciones y edificaciones", use: "general", normalSide: "Credit" },
    { code: "159215", name: "Depreciación acumulada de equipo de oficina", use: "general", normalSide: "Credit" },
    { code: "159220", name: "Depreciación acumulada de equipo de computación y comunicación", use: "general", normalSide: "Credit" },
    { code: "159235", name: "Depreciación acumulada de flota y equipo de transporte", use: "general", normalSide: "Credit" },
    { code: "170520", name: "Seguros y fianzas pagados por anticipado", use: "general" },
    { code: "170545", name: "Suscripciones pagadas por anticipado", use: "general" },
    // 2 Pasivo
    { code: "219505", name: "Obligaciones con particulares", use: "general" },
    { code: "233595", name: "Otros costos y gastos por pagar", use: "general" },
    { code: "238020", name: "Reintegros por pagar", use: "general" },
    { code: "240405", name: "Impuesto de renta por pagar, vigencia corriente", use: "general" },
    { code: "270515", name: "Arrendamientos recibidos por anticipado", use: "general" },
    { code: "280505", name: "Anticipos de clientes", use: "general" },
    { code: "281020", name: "Depósitos recibidos en garantía de contratos", use: "general" },
    // 3 Patrimonio
    { code: "313001", name: "Patrimonio de apertura", use: "openingBalance" },
    // 4 Ingresos
    { code: "421005", name: "Intereses", use: "income" },
    { code: "421020", name: "Diferencia en cambio (ingreso)", use: "general" },
    { code: "421505", name: "Dividendos de sociedades anónimas", use: "income" },
    { code: "42201001", name: "Arrendamientos de vivienda", use: "income" },
    { code: "42201002", name: "Alojamiento de corta estancia", use: "income" },
    { code: "423005", name: "Honorarios por asesorías", use: "income" },
    { code: "424005", name: "Utilidad en venta de acciones", use: "general" },
    { code: "429543", name: "Premios", use: "income" },
    { code: "429545", name: "Bonificaciones", use: "income" },
    { code: "42959501", name: "Salario", use: "income" },
    { code: "42959502", name: "Regalos y apoyos recibidos", use: "income" },
    { code: "42959595", name: "Otros ingresos", use: "income" },
    // 5 Gastos
    { code: "511025", name: "Asesoría jurídica", use: "expense" },
    { code: "511030", name: "Asesoría financiera", use: "expense" },
    { code: "511515", name: "Impuesto predial", use: "expense" },
    { code: "511540", name: "Impuesto de vehículos", use: "expense" },
    { code: "51159501", name: "Gravamen a los movimientos financieros (4x1000)", use: "expense" },
    { code: "512010", name: "Arrendamiento de vivienda", use: "expense" },
    { code: "513020", name: "Seguro de vida", use: "expense" },
    { code: "513040", name: "Seguro de vehículo", use: "expense" },
    { code: "513075", name: "SOAT", use: "expense" },
    { code: "513095", name: "Otros seguros", use: "expense" },
    { code: "513505", name: "Aseo y vigilancia", use: "expense" },
    { code: "513525", name: "Acueducto y alcantarillado", use: "expense" },
    { code: "513530", name: "Energía eléctrica", use: "expense" },
    { code: "513535", name: "Teléfono e internet", use: "expense" },
    { code: "513550", name: "Transporte, fletes y acarreos", use: "expense" },
    { code: "513555", name: "Gas", use: "expense" },
    { code: "51359501", name: "Software y servicios digitales", use: "expense" },
    { code: "514510", name: "Mantenimiento de vivienda", use: "expense" },
    { code: "514525", name: "Mantenimiento de equipo de computación y comunicación", use: "expense" },
    { code: "514540", name: "Mantenimiento de vehículos", use: "expense" },
    { code: "515505", name: "Alojamiento y manutención en viajes", use: "expense" },
    { code: "515515", name: "Pasajes aéreos", use: "expense" },
    { code: "515520", name: "Pasajes terrestres", use: "expense" },
    { code: "516005", name: "Depreciación de construcciones y edificaciones", use: "general" },
    { code: "516015", name: "Depreciación de equipo de oficina", use: "general" },
    { code: "516020", name: "Depreciación de equipo de computación y comunicación", use: "general" },
    { code: "516035", name: "Depreciación de flota y equipo de transporte", use: "general" },
    { code: "519510", name: "Libros, suscripciones, periódicos y revistas", use: "expense" },
    { code: "519525", name: "Elementos de aseo y cafetería", use: "expense" },
    { code: "519535", name: "Combustibles y lubricantes", use: "expense" },
    { code: "519545", name: "Taxis y buses", use: "expense" },
    { code: "519560", name: "Restaurantes y cafeterías", use: "expense" },
    { code: "519565", name: "Parqueaderos", use: "expense" },
    { code: "51959501", name: "Mercado y alimentos del hogar", use: "expense" },
    { code: "51959502", name: "Salud y medicamentos", use: "expense" },
    { code: "51959503", name: "Cuidado personal", use: "expense" },
    { code: "51959504", name: "Ropa y calzado", use: "expense" },
    { code: "51959505", name: "Educación", use: "expense" },
    { code: "51959506", name: "Deporte y bienestar", use: "expense" },
    { code: "51959507", name: "Entretenimiento y recreación", use: "expense" },
    { code: "51959508", name: "Regalos y apoyo familiar", use: "expense" },
    { code: "51959509", name: "Mascotas", use: "expense" },
    { code: "51959510", name: "Tecnología y accesorios", use: "expense" },
    { code: "51959595", name: "Otros gastos personales", use: "expense" },
    { code: "530505", name: "Gastos bancarios", use: "expense" },
    { code: "530515", name: "Comisiones financieras", use: "expense" },
    { code: "530520", name: "Intereses", use: "expense" },
    { code: "530525", name: "Diferencia en cambio (gasto)", use: "general" },
    { code: "531005", name: "Pérdida en venta de inversiones", use: "general" },
    { code: "531015", name: "Pérdida en venta de propiedades, planta y equipo", use: "general" },
    { code: "539520", name: "Multas, sanciones y litigios", use: "expense" },
    { code: "539525", name: "Donaciones", use: "expense" },
    { code: "540505", name: "Impuesto de renta y complementarios", use: "expense" },
  ],
  summaryNames: {
    "1": "Activo",
    "11": "Disponible",
    "1105": "Caja",
    "110505": "Caja general",
    "1110": "Bancos",
    "111005": "Moneda nacional",
    "1120": "Cuentas de ahorro",
    "112005": "Bancos",
    "12": "Inversiones",
    "1225": "Certificados",
    "1245": "Derechos fiduciarios",
    "13": "Deudores",
    "1330": "Anticipos y avances",
    "1345": "Ingresos por cobrar",
    "1370": "Préstamos a particulares",
    "1380": "Deudores varios",
    "15": "Propiedades, planta y equipo",
    "1504": "Terrenos",
    "1516": "Construcciones y edificaciones",
    "1524": "Equipo de oficina",
    "1528": "Equipo de computación y comunicación",
    "1540": "Flota y equipo de transporte",
    "1592": "Depreciación acumulada",
    "17": "Diferidos",
    "1705": "Gastos pagados por anticipado",
    "2": "Pasivo",
    "21": "Obligaciones financieras",
    "2105": "Bancos nacionales",
    "210510": "Pagarés",
    "2195": "Otras obligaciones",
    "23": "Cuentas por pagar",
    "2335": "Costos y gastos por pagar",
    "2380": "Acreedores varios",
    "24": "Impuestos, gravámenes y tasas",
    "2404": "De renta y complementarios",
    "27": "Diferidos",
    "2705": "Ingresos recibidos por anticipado",
    "28": "Otros pasivos",
    "2805": "Anticipos y avances recibidos",
    "2810": "Depósitos recibidos",
    "3": "Patrimonio",
    "31": "Capital social",
    "3130": "Capital de personas naturales",
    "4": "Ingresos",
    "42": "No operacionales",
    "4210": "Financieros",
    "4215": "Dividendos y participaciones",
    "4220": "Arrendamientos",
    "422010": "Construcciones y edificios",
    "4230": "Honorarios",
    "4240": "Utilidad en venta de inversiones",
    "4295": "Diversos",
    "429595": "Otros",
    "5": "Gastos",
    "51": "Operacionales de administración",
    "5110": "Honorarios",
    "5115": "Impuestos",
    "511595": "Otros",
    "5120": "Arrendamientos",
    "5130": "Seguros",
    "5135": "Servicios",
    "513595": "Otros",
    "5145": "Mantenimiento y reparaciones",
    "5155": "Gastos de viaje",
    "5160": "Depreciaciones",
    "5195": "Diversos",
    "519595": "Otros",
    "53": "No operacionales",
    "5305": "Financieros",
    "5310": "Pérdida en venta y retiro de bienes",
    "5395": "Gastos diversos",
    "54": "Impuesto de renta y complementarios",
    "5405": "Impuesto de renta y complementarios",
  },
} satisfies ChartOfAccountsTemplate;
