/*
 * COA Template for an English-language Personal Workspace, mirroring co-puc-personal@1.
 * US GAAP prescribes no chart of accounts, so codes are application-owned: the first
 * digit is the class, the second the group. Reporting concepts cite the FASB US GAAP
 * Taxonomy 2026 (https://xbrl.fasb.org/us-gaap/2026/elts/us-gaap-2026.xsd) only where an
 * element fits; personal concepts such as salary received or groceries have none,
 * because the taxonomy describes a reporting entity, not a household.
 * Cohesive data file: one template, one version; see ADR-0083.
 */
import type { ChartOfAccountsTemplate } from "../types";

export const usGaapPersonalTemplate = {
  version: "us-gaap-personal@1",
  natureByClass: {
    "1": "Asset",
    "2": "Liability",
    "3": "Equity",
    "4": "Revenue",
    "5": "Expense",
    "6": "Expense",
  },
  defaults: { expense: "5599", income: "4990", openingBalance: "3010" },
  financialAccountParents: {
    cash: "1010",
    bankAccount: "1020",
    savingsAccount: "1030",
    creditCard: "2010",
    loan: "2110",
  },
  accounts: [
    // 1 Assets
    { code: "1110", name: "Certificates of deposit", use: "general", reportingConcept: "us-gaap:CertificatesOfDepositAtCarryingValue" },
    { code: "1120", name: "Investment fund units", use: "general", reportingConcept: "us-gaap:EquitySecuritiesFvNi" },
    { code: "1210", name: "Advances to suppliers", use: "general" },
    { code: "1220", name: "Dividends receivable", use: "general", reportingConcept: "us-gaap:DividendsReceivable" },
    { code: "1230", name: "Interest receivable", use: "general", reportingConcept: "us-gaap:InterestReceivable" },
    { code: "1240", name: "Rent receivable", use: "general" },
    { code: "1250", name: "Loans to individuals, secured", use: "general", reportingConcept: "us-gaap:NotesReceivableGross" },
    { code: "1260", name: "Loans to individuals, unsecured", use: "general", reportingConcept: "us-gaap:NotesReceivableGross" },
    { code: "1270", name: "Payments made on behalf of others", use: "general", reportingConcept: "us-gaap:OtherReceivables" },
    { code: "1310", name: "Prepaid insurance", use: "general", reportingConcept: "us-gaap:PrepaidInsurance" },
    { code: "1320", name: "Prepaid subscriptions", use: "general", reportingConcept: "us-gaap:OtherPrepaidExpenseCurrent" },
    { code: "1510", name: "Land", use: "general", reportingConcept: "us-gaap:Land" },
    { code: "1520", name: "Buildings", use: "general", reportingConcept: "us-gaap:BuildingsAndImprovementsGross" },
    { code: "1530", name: "Furniture and fixtures", use: "general", reportingConcept: "us-gaap:FurnitureAndFixturesGross" },
    { code: "1540", name: "Computer equipment", use: "general", reportingConcept: "us-gaap:PropertyPlantAndEquipmentGross" },
    { code: "1550", name: "Vehicles", use: "general", reportingConcept: "us-gaap:PropertyPlantAndEquipmentGross" },
    { code: "1560", name: "Motorcycles", use: "general", reportingConcept: "us-gaap:PropertyPlantAndEquipmentGross" },
    { code: "1591", name: "Accumulated depreciation, buildings", use: "general", normalSide: "Credit", reportingConcept: "us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment" },
    { code: "1592", name: "Accumulated depreciation, furniture and fixtures", use: "general", normalSide: "Credit", reportingConcept: "us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment" },
    { code: "1593", name: "Accumulated depreciation, computer equipment", use: "general", normalSide: "Credit", reportingConcept: "us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment" },
    { code: "1594", name: "Accumulated depreciation, vehicles", use: "general", normalSide: "Credit", reportingConcept: "us-gaap:AccumulatedDepreciationDepletionAndAmortizationPropertyPlantAndEquipment" },
    // 2 Liabilities
    { code: "2120", name: "Loans from individuals", use: "general", reportingConcept: "us-gaap:OtherNotesPayable" },
    { code: "2210", name: "Accrued expenses", use: "general", reportingConcept: "us-gaap:AccruedLiabilitiesCurrent" },
    { code: "2220", name: "Reimbursements payable", use: "general", reportingConcept: "us-gaap:AccountsPayableOtherCurrent" },
    { code: "2230", name: "Income taxes payable", use: "general", reportingConcept: "us-gaap:AccruedIncomeTaxesCurrent" },
    { code: "2310", name: "Rent received in advance", use: "general", reportingConcept: "us-gaap:DeferredRevenueCurrent" },
    { code: "2320", name: "Customer advances", use: "general", reportingConcept: "us-gaap:ContractWithCustomerLiabilityCurrent" },
    { code: "2330", name: "Security deposits received", use: "general", reportingConcept: "us-gaap:SecurityDepositLiability" },
    // 3 Net worth
    { code: "3010", name: "Opening balance equity", use: "openingBalance" },
    // 4 Revenue
    { code: "4010", name: "Salary and wages", use: "income" },
    { code: "4020", name: "Bonuses", use: "income" },
    { code: "4030", name: "Consulting fees", use: "income", reportingConcept: "us-gaap:RevenueFromContractWithCustomerExcludingAssessedTax" },
    { code: "4110", name: "Interest income", use: "income", reportingConcept: "us-gaap:InvestmentIncomeInterest" },
    { code: "4120", name: "Dividend income", use: "income", reportingConcept: "us-gaap:InvestmentIncomeDividend" },
    { code: "4130", name: "Gain on sale of investments", use: "general", reportingConcept: "us-gaap:GainLossOnInvestments" },
    { code: "4140", name: "Foreign exchange gains", use: "general", reportingConcept: "us-gaap:ForeignCurrencyTransactionGainBeforeTax" },
    { code: "4210", name: "Long-term rental income", use: "income", reportingConcept: "us-gaap:RentalIncomeNonoperating" },
    { code: "4220", name: "Short-stay accommodation income", use: "income", reportingConcept: "us-gaap:OccupancyNet" },
    { code: "4910", name: "Prizes", use: "income", reportingConcept: "us-gaap:OtherNonoperatingIncome" },
    { code: "4920", name: "Gifts and support received", use: "income" },
    { code: "4990", name: "Other income", use: "income", reportingConcept: "us-gaap:OtherNonoperatingIncome" },
    // 5 Living expenses
    { code: "5010", name: "Rent", use: "expense", reportingConcept: "us-gaap:OperatingLeaseCost" },
    { code: "5020", name: "Home repairs and maintenance", use: "expense", reportingConcept: "us-gaap:CostOfPropertyRepairsAndMaintenance" },
    { code: "5030", name: "Property tax", use: "expense", reportingConcept: "us-gaap:RealEstateTaxExpense" },
    { code: "5040", name: "Cleaning and security services", use: "expense" },
    { code: "5110", name: "Water and sewer", use: "expense" },
    { code: "5120", name: "Electricity", use: "expense" },
    { code: "5130", name: "Gas", use: "expense" },
    { code: "5140", name: "Phone and internet", use: "expense", reportingConcept: "us-gaap:Communication" },
    { code: "5150", name: "Software and digital services", use: "expense", reportingConcept: "us-gaap:InformationTechnologyAndDataProcessing" },
    { code: "5160", name: "Books and subscriptions", use: "expense" },
    { code: "5210", name: "Fuel", use: "expense", reportingConcept: "us-gaap:FuelCosts" },
    { code: "5220", name: "Taxis and public transit", use: "expense" },
    { code: "5230", name: "Parking", use: "expense" },
    { code: "5240", name: "Vehicle repairs and maintenance", use: "expense" },
    { code: "5250", name: "Vehicle tax", use: "expense", reportingConcept: "us-gaap:TaxesOther" },
    { code: "5260", name: "Shipping and moving", use: "expense" },
    { code: "5310", name: "Groceries", use: "expense" },
    { code: "5320", name: "Restaurants and cafés", use: "expense" },
    { code: "5330", name: "Household supplies", use: "expense", reportingConcept: "us-gaap:SuppliesExpense" },
    { code: "5410", name: "Life insurance", use: "expense", reportingConcept: "us-gaap:GeneralInsuranceExpense" },
    { code: "5420", name: "Vehicle insurance", use: "expense", reportingConcept: "us-gaap:GeneralInsuranceExpense" },
    { code: "5430", name: "Compulsory traffic accident insurance", use: "expense", reportingConcept: "us-gaap:GeneralInsuranceExpense" },
    { code: "5440", name: "Other insurance", use: "expense", reportingConcept: "us-gaap:GeneralInsuranceExpense" },
    { code: "5510", name: "Health and medicine", use: "expense" },
    { code: "5520", name: "Personal care", use: "expense" },
    { code: "5530", name: "Clothing and footwear", use: "expense" },
    { code: "5540", name: "Education", use: "expense" },
    { code: "5550", name: "Sports and wellness", use: "expense" },
    { code: "5560", name: "Entertainment and recreation", use: "expense" },
    { code: "5570", name: "Gifts and family support", use: "expense" },
    { code: "5580", name: "Pets", use: "expense" },
    { code: "5590", name: "Technology and accessories", use: "expense" },
    { code: "5599", name: "Other personal expenses", use: "expense" },
    { code: "5610", name: "Legal fees", use: "expense", reportingConcept: "us-gaap:LegalFees" },
    { code: "5620", name: "Financial advisory fees", use: "expense", reportingConcept: "us-gaap:ProfessionalFees" },
    { code: "5630", name: "Financial transaction tax", use: "expense", reportingConcept: "us-gaap:TaxesOther" },
    { code: "5640", name: "Income tax", use: "expense", reportingConcept: "us-gaap:IncomeTaxExpenseBenefit" },
    { code: "5650", name: "Fines and penalties", use: "expense" },
    { code: "5660", name: "Donations", use: "expense" },
    { code: "5710", name: "Travel lodging and meals", use: "expense", reportingConcept: "us-gaap:TravelAndEntertainmentExpense" },
    { code: "5720", name: "Airfare", use: "expense", reportingConcept: "us-gaap:TravelAndEntertainmentExpense" },
    { code: "5730", name: "Intercity ground fares", use: "expense", reportingConcept: "us-gaap:TravelAndEntertainmentExpense" },
    // 6 Financial costs, depreciation, and losses
    { code: "6010", name: "Bank fees", use: "expense" },
    { code: "6020", name: "Financial commissions", use: "expense" },
    { code: "6030", name: "Interest expense", use: "expense", reportingConcept: "us-gaap:InterestExpense" },
    { code: "6040", name: "Foreign exchange losses", use: "general", reportingConcept: "us-gaap:ForeignCurrencyTransactionLossBeforeTax" },
    { code: "6110", name: "Depreciation, buildings", use: "general", reportingConcept: "us-gaap:Depreciation" },
    { code: "6120", name: "Depreciation, furniture and fixtures", use: "general", reportingConcept: "us-gaap:Depreciation" },
    { code: "6130", name: "Depreciation, computer equipment", use: "general", reportingConcept: "us-gaap:Depreciation" },
    { code: "6140", name: "Depreciation, vehicles", use: "general", reportingConcept: "us-gaap:Depreciation" },
    { code: "6150", name: "Loss on sale of investments", use: "general", reportingConcept: "us-gaap:GainLossOnInvestments" },
    { code: "6160", name: "Loss on disposal of property and equipment", use: "general", reportingConcept: "us-gaap:GainLossOnDispositionOfAssets" },
  ],
  summaryNames: {
    "1": "Assets",
    "10": "Cash and cash equivalents",
    "1010": "Cash on hand",
    "1020": "Checking accounts",
    "1030": "Savings accounts",
    "11": "Investments",
    "12": "Receivables",
    "13": "Prepaid expenses",
    "15": "Property and equipment",
    "2": "Liabilities",
    "20": "Credit cards",
    "2010": "Credit cards payable",
    "21": "Borrowings",
    "2110": "Loans payable",
    "22": "Payables and accrued liabilities",
    "23": "Deferred revenue and deposits",
    "3": "Net worth",
    "30": "Net worth",
    "4": "Revenue",
    "40": "Earned income",
    "41": "Investment income",
    "42": "Rental income",
    "49": "Other income",
    "5": "Living expenses",
    "50": "Housing",
    "51": "Utilities and communication",
    "52": "Transportation",
    "53": "Food and household",
    "54": "Insurance",
    "55": "Personal and family",
    "56": "Professional services and taxes",
    "57": "Travel",
    "6": "Financial and other expenses",
    "60": "Financial costs",
    "61": "Depreciation and losses",
  },
} satisfies ChartOfAccountsTemplate;
